# Generated by Django 5.2.6 on 2025-09-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('role_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
