# Generated by Django 5.2.6 on 2025-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='rule_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='rule_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PENDING_VERIFICATION', 'Pendiente de Verificación'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=25),
        ),
    ]
