# Generated by Django 5.2.6 on 2025-09-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0002_invite_rule_channel_id_invite_rule_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo del rol (ej: 'Nivel 1', 'VIP', 'Staff')", max_length=100, unique=True)),
                ('role_id', models.CharField(db_index=True, help_text='ID del rol de Discord', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del rol y sus permisos')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se incluirá en las verificaciones de acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol de Acceso',
                'verbose_name_plural': 'Roles de Acceso',
                'ordering': ['name'],
            },
        ),
    ]
