# Generated by Django 5.2.6 on 2025-09-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0003_accessrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre identificativo de la configuración (ej: 'guild_id', 'rules_channel')", max_length=100, unique=True)),
                ('value', models.CharField(help_text='Valor de la configuración (ID de Discord, número, etc.)', max_length=200)),
                ('configuration_type', models.CharField(choices=[('guild', 'Guild/Servidor'), ('channel', 'Canal'), ('message', 'Mensaje'), ('category', 'Categoría'), ('general', 'General')], help_text='Tipo de configuración', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descripción de para qué se usa esta configuración')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, el bot la usará')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Bot',
                'verbose_name_plural': 'Configuraciones del Bot',
                'ordering': ['configuration_type', 'name'],
            },
        ),
    ]
