# Generated by Django 5.2.6 on 2025-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0004_botconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiguration',
            name='value',
            field=models.CharField(blank=True, help_text='Valor de la configuración (ID de Discord, número, etc.)', max_length=200),
        ),
    ]
