# Generated by Django 5.2.6 on 2025-09-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0005_alter_botconfiguration_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotmartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, help_text='ID del producto en Hotmart', max_length=100, unique=True)),
                ('product_name', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('discord_role_id', models.CharField(help_text='ID del rol de Discord a asignar', max_length=100)),
                ('is_subscription', models.BooleanField(default=True, help_text='Si es un producto de suscripción recurrente')),
                ('is_active', models.BooleanField(default=True, help_text='Si el producto está activo')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad del producto (mayor = mejor plan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Hotmart',
                'verbose_name_plural': 'Productos Hotmart',
                'ordering': ['-priority', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='HotmartSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_code', models.CharField(db_index=True, help_text='Código único del suscriptor en Hotmart', max_length=100, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Email del suscriptor', max_length=255)),
                ('plan_id', models.CharField(help_text='ID del plan de suscripción', max_length=100)),
                ('plan_name', models.CharField(help_text='Nombre del plan', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CANCELLED', 'Cancelada'), ('SUSPENDED', 'Suspendida'), ('EXPIRED', 'Expirada'), ('PENDING_PAYMENT', 'Pendiente de Pago')], default='ACTIVE', max_length=20)),
                ('member_id', models.CharField(blank=True, db_index=True, help_text='ID del miembro en Discord', max_length=100, null=True)),
                ('current_role_id', models.CharField(blank=True, help_text='Rol actual asignado', max_length=100, null=True)),
                ('next_charge_date', models.DateTimeField(blank=True, help_text='Fecha del próximo cobro', null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, help_text='Fecha de cancelación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Última sincronización con Discord', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='invitation_roles.hotmartproduct')),
            ],
            options={
                'verbose_name': 'Suscripción Hotmart',
                'verbose_name_plural': 'Suscripciones Hotmart',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotmartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='ID único de la transacción', max_length=100, unique=True)),
                ('hotmart_event_id', models.CharField(db_index=True, help_text='ID del evento de Hotmart', max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('PURCHASE_APPROVED', 'Compra Aprobada'), ('PURCHASE_COMPLETE', 'Compra Completada'), ('PURCHASE_REFUNDED', 'Compra Reembolsada'), ('PURCHASE_PROTEST', 'Disputa de Compra'), ('SUBSCRIPTION_CANCELLATION', 'Cancelación de Suscripción'), ('SWITCH_PLAN', 'Cambio de Plan'), ('UPDATE_SUBSCRIPTION_CHARGE_DATE', 'Actualización de Fecha de Cobro')], help_text='Tipo de evento de Hotmart', max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'Aprobada'), ('COMPLETED', 'Completada'), ('REFUNDED', 'Reembolsada'), ('DISPUTE', 'Disputa'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendiente')], max_length=20)),
                ('transaction_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='BRL', max_length=10)),
                ('raw_webhook_data', models.JSONField(help_text='Datos completos del webhook de Hotmart')),
                ('processed', models.BooleanField(default=False, help_text='Si la transacción fue procesada correctamente')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invitation_roles.hotmartproduct')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='invitation_roles.hotmartsubscription')),
            ],
            options={
                'verbose_name': 'Transacción Hotmart',
                'verbose_name_plural': 'Transacciones Hotmart',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotmartsubscription',
            index=models.Index(fields=['email', 'status'], name='invitation__email_c7ae7e_idx'),
        ),
        migrations.AddIndex(
            model_name='hotmartsubscription',
            index=models.Index(fields=['subscriber_code', 'status'], name='invitation__subscri_c733be_idx'),
        ),
        migrations.AddIndex(
            model_name='hotmarttransaction',
            index=models.Index(fields=['email', 'processed'], name='invitation__email_2c5de1_idx'),
        ),
        migrations.AddIndex(
            model_name='hotmarttransaction',
            index=models.Index(fields=['event_type', 'created_at'], name='invitation__event_t_3debea_idx'),
        ),
    ]
