# Generated by Django 5.2.6 on 2025-10-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0006_hotmartproduct_hotmartsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiguration',
            name='configuration_type',
            field=models.CharField(choices=[('guild', 'Guild/Servidor'), ('channel', 'Canal'), ('message', 'Mensaje'), ('category', 'Categoría'), ('general', 'General'), ('api_key', 'API Key')], help_text='Tipo de configuración', max_length=20),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='value',
            field=models.TextField(blank=True, help_text='Valor de la configuración (ID de Discord, número, API key, etc.)'),
        ),
    ]
