# Generated by Django 5.2.6 on 2025-12-21 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_roles', '0007_alter_botconfiguration_configuration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('role_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Compartido',
                'verbose_name_plural': 'Links Compartidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedInviteRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pendiente de Verificación'), ('USED', 'Usado')], default='PENDING_VERIFICATION', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='invitation_roles.sharedinvitelink')),
            ],
            options={
                'verbose_name': 'Redención de Link Compartido',
                'verbose_name_plural': 'Redenciones de Links Compartidos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('link', 'member_id'), name='uniq_shared_invite_link_member')],
            },
        ),
    ]
