# Generated by Django 5.2.6 on 2025-10-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatbotusage',
            name='unique_user_date',
        ),
        migrations.AlterUniqueTogether(
            name='chatbotusage',
            unique_together={('user_id', 'date')},
        ),
    ]
