# Generated by Django 5.2.6 on 2025-11-29 17:53

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_ai', '0002_remove_chatbotusage_unique_user_date_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ChatbotKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Contenido del chunk (~500 tokens)')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, help_text='Vector embedding de OpenAI')),
                ('source_file', models.CharField(help_text='Archivo de origen', max_length=255)),
                ('course', models.CharField(choices=[('imax_launch', 'IMAX Launch'), ('imax_pro', 'IMAX Pro')], db_index=True, max_length=20)),
                ('module', models.CharField(blank=True, help_text='Módulo extraído del nombre', max_length=100)),
                ('chunk_index', models.IntegerField(default=0, help_text='Índice del chunk en el archivo')),
                ('token_count', models.IntegerField(default=0, help_text='Número de tokens en el chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chunk de Conocimiento',
                'verbose_name_plural': 'Chunks de Conocimiento',
                'ordering': ['course', 'source_file', 'chunk_index'],
                'indexes': [models.Index(fields=['course', 'source_file'], name='chatbot_ai__course_3f4704_idx')],
            },
        ),
    ]
